GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "test5",
    "author": "Luis222",
    "url": "https://reddiasdasdat.com",
    "userId": "61a547fab91809a89e4bf1ec"
}
###
DELETE http://localhost:3003/api/blogs/61a3f95ae7e210896b79bf82
